name: Download a binary
on:
  release:
    types:
      - created
jobs:
  download-and-add-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Download file
        uses: actions/download-artifact@v2
        with:
          name: tsmaster_${{ github.ref_name }}.exe
          url: http://www.tosun.tech/TOSUNSoftware/TSMaster_Setup_alpha.exe

      - name: Add tsmaster to release assets
        id: upload_asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: tsmaster_${{ github.ref_name }}.exe
          asset_content_type: application/octet-stream
